name: prevencion_cardiovascular
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

   # Firebase
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.4
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6
  firebase_messaging: ^14.1.2

  #Get
  # get: ^4.6.5
  get_storage: 2.0.3

  #googleapis
  googleapis_auth: ^1.3.1

  # Others
  intl: ^0.17.0
  url_launcher: ^6.0.3
  material_design_icons_flutter:
  file_picker: ^5.2.2
  permission_handler: ^10.0.0
  flutter_credit_card: ^3.0.1
  cached_network_image: ^3.2.0
  flutter_native_splash: ^2.1.1
  geocoding: ^2.0.4
  syncfusion_flutter_pdfviewer: ^20.1.55-beta
  image_picker: ^0.8.4+11
  flutter_multi_formatter: ^2.5.1
  http: ^0.13.4
  card_swiper: ^2.0.3
  connectivity_plus: ^3.0.2
  enum_to_string: ^2.0.1
  flutter_image_compress: ^1.1.0
  intl_phone_field: ^3.1.0
  location: ^4.2.0
  dots_indicator: ^2.1.0
  country_code_picker: ^2.0.2
  google_maps_flutter:
    git:
      url: https://github.com/lukaskurz/plugins
      path: packages/google_maps_flutter/google_maps_flutter
      ref: main

dev_dependencies:
  flutter_lints: ^2.0.1
  lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/